server:
  port: 8762
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    appname: user-service
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



